import type { Campaign } from "../hooks/useCampaigns";

export const mockCampaigns: Campaign[] = [
  {
    id: "1",
    campaignName: "Summer Sale",
    keywords: ["summer", "sale", "discount", "promo"],
    bidAmount: 150.0,
    campaignFund: 5000.0,
    status: "Active",
    town: "Cracow",
    radius: 50,
  },
  {
    id: "2",
    campaignName: "Winter Clearance",
    keywords: ["winter", "clearance", "deal"],
    bidAmount: 200.0,
    campaignFund: 7500.0,
    status: "Inactive",
    town: "Warsaw",
    radius: 30,
  },
  {
    id: "3",
    campaignName: "Back to School",
    keywords: ["school", "books", "supplies", "promotion"],
    bidAmount: 120.0,
    campaignFund: 3000.0,
    status: "Active",
    town: "Gdansk",
    radius: 40,
  },
  {
    id: "4",
    campaignName: "Holiday Specials",
    keywords: ["holiday", "gift", "special", "sale"],
    bidAmount: 180.0,
    campaignFund: 6000.0,
    status: "Active",
    town: "Poznan",
    radius: 60,
  },
  {
    id: "5",
    campaignName: "Flash Deals",
    keywords: ["flash", "deal", "limited", "offer"],
    bidAmount: 100.0,
    campaignFund: 2500.0,
    status: "Inactive",
    town: "Lodz",
    radius: 25,
  },
  {
    id: "6",
    campaignName: "Spring Promo",
    keywords: ["spring", "promo", "discount"],
    bidAmount: 130.0,
    campaignFund: 4000.0,
    status: "Active",
    town: "Wroclaw",
    radius: 35,
  },
  {
    id: "7",
    campaignName: "Tech Launch",
    keywords: ["tech", "launch", "new", "gadget"],
    bidAmount: 220.0,
    campaignFund: 8000.0,
    status: "Active",
    town: "Warsaw",
    radius: 55,
  },
  {
    id: "8",
    campaignName: "Eco Sale",
    keywords: ["eco", "green", "sustainable", "offer"],
    bidAmount: 90.0,
    campaignFund: 2000.0,
    status: "Inactive",
    town: "Gdansk",
    radius: 20,
  },
  {
    id: "9",
    campaignName: "Fitness Promo",
    keywords: ["fitness", "gym", "health", "promo"],
    bidAmount: 140.0,
    campaignFund: 3500.0,
    status: "Active",
    town: "Cracow",
    radius: 45,
  },
  {
    id: "10",
    campaignName: "Gadget Discounts",
    keywords: ["gadget", "electronics", "discount", "deal"],
    bidAmount: 200.0,
    campaignFund: 7000.0,
    status: "Inactive",
    town: "Poznan",
    radius: 50,
  },
  {
    id: "11",
    campaignName: "Fashion Week",
    keywords: ["fashion", "week", "sale", "promo"],
    bidAmount: 170.0,
    campaignFund: 6000.0,
    status: "Active",
    town: "Warsaw",
    radius: 40,
  },
  {
    id: "12",
    campaignName: "Weekend Deals",
    keywords: ["weekend", "deal", "limited"],
    bidAmount: 110.0,
    campaignFund: 3000.0,
    status: "Active",
    town: "Lodz",
    radius: 30,
  },
  {
    id: "13",
    campaignName: "Gourmet Specials",
    keywords: ["gourmet", "food", "special", "sale"],
    bidAmount: 160.0,
    campaignFund: 4500.0,
    status: "Inactive",
    town: "Gdansk",
    radius: 35,
  },
  {
    id: "14",
    campaignName: "Outdoor Adventures",
    keywords: ["outdoor", "adventure", "gear", "promo"],
    bidAmount: 190.0,
    campaignFund: 5000.0,
    status: "Active",
    town: "Wroclaw",
    radius: 60,
  },
  {
    id: "15",
    campaignName: "Luxury Collection",
    keywords: ["luxury", "collection", "premium", "sale"],
    bidAmount: 250.0,
    campaignFund: 9000.0,
    status: "Inactive",
    town: "Cracow",
    radius: 70,
  },
  {
    id: "16",
    campaignName: "Home Office Upgrade",
    keywords: ["home", "office", "desk", "chair"],
    bidAmount: 210.0,
    campaignFund: 6500.0,
    status: "Active",
    town: "Wroclaw",
    radius: 45,
  },
  {
    id: "17",
    campaignName: "Pet Essentials",
    keywords: ["pet", "food", "toy", "supplies"],
    bidAmount: 130.0,
    campaignFund: 3200.0,
    status: "Inactive",
    town: "Lodz",
    radius: 30,
  },
  {
    id: "18",
    campaignName: "Smart Home",
    keywords: ["smart", "home", "automation", "tech"],
    bidAmount: 240.0,
    campaignFund: 8500.0,
    status: "Active",
    town: "Warsaw",
    radius: 50,
  },
  {
    id: "19",
    campaignName: "Gaming Gear",
    keywords: ["gaming", "gear", "console", "pc"],
    bidAmount: 260.0,
    campaignFund: 9500.0,
    status: "Active",
    town: "Poznan",
    radius: 65,
  },
  {
    id: "20",
    campaignName: "Travel Accessories",
    keywords: ["travel", "bag", "accessory", "trip"],
    bidAmount: 155.0,
    campaignFund: 4200.0,
    status: "Inactive",
    town: "Cracow",
    radius: 40,
  },
  {
    id: "21",
    campaignName: "Kitchen Renovation",
    keywords: ["kitchen", "reno", "cookware", "appliance"],
    bidAmount: 300.0,
    campaignFund: 12000.0,
    status: "Active",
    town: "Cracow",
    radius: 35,
  },
  {
    id: "22",
    campaignName: "Cycling Gear",
    keywords: ["bike", "cycling", "helmet", "gear"],
    bidAmount: 140.0,
    campaignFund: 4000.0,
    status: "Active",
    town: "Wroclaw",
    radius: 50,
  },
  {
    id: "23",
    campaignName: "Art Supplies",
    keywords: ["art", "paint", "canvas", "draw"],
    bidAmount: 110.0,
    campaignFund: 2200.0,
    status: "Inactive",
    town: "Lodz",
    radius: 20,
  },
  {
    id: "24",
    campaignName: "Baby Essentials",
    keywords: ["baby", "diaper", "stoller", "toy"],
    bidAmount: 160.0,
    campaignFund: 5500.0,
    status: "Active",
    town: "Warsaw",
    radius: 40,
  },
  {
    id: "25",
    campaignName: "Car Accessories",
    keywords: ["car", "auto", "accessory", "part"],
    bidAmount: 190.0,
    campaignFund: 6800.0,
    status: "Inactive",
    town: "Poznan",
    radius: 60,
  },
  {
    id: "26",
    campaignName: "Music Festival",
    keywords: ["music", "festival", "ticket", "concert"],
    bidAmount: 250.0,
    campaignFund: 15000.0,
    status: "Active",
    town: "Gdansk",
    radius: 80,
  },
  {
    id: "27",
    campaignName: "Digital Marketing",
    keywords: ["marketing", "seo", "digital", "social"],
    bidAmount: 320.0,
    campaignFund: 20000.0,
    status: "Active",
    town: "Warsaw",
    radius: 100,
  },
  {
    id: "28",
    campaignName: "Local Events",
    keywords: ["event", "local", "community", "meetup"],
    bidAmount: 80.0,
    campaignFund: 1500.0,
    status: "Inactive",
    town: "Cracow",
    radius: 15,
  },
  {
    id: "29",
    campaignName: "Language Courses",
    keywords: ["language", "course", "learn", "class"],
    bidAmount: 175.0,
    campaignFund: 4800.0,
    status: "Active",
    town: "Wroclaw",
    radius: 25,
  },
  {
    id: "30",
    campaignName: "Wellness Retreat",
    keywords: ["wellness", "spa", "retreat", "health"],
    bidAmount: 280.0,
    campaignFund: 10000.0,
    status: "Active",
    town: "Gdansk",
    radius: 90,
  },
];
